### ISSUE TITLE
implementation of protocol

### ISSUE THREAD

**Issue by dadosch** [dadosch/barrier-android#1]
I think a good way of approaching this would be to have a interface "Message". This way, we can have separate Java-classes for each message-type (see https://github.com/debauchee/barrier/blob/fc045fc79326cef966405b1cc578e8f062ae5294/src/lib/barrier/protocol_types.cpp).

For the messages which need additional data for sending, the data can simply be passed in the constructor. When receiving, a static "receive" Method can be used, which returns an instance of the specific message class with the received data:

```
public interface Message {

}

```

```

public class HelloMessage implements Message {
    public HelloMessage(Integer major, Integer minor) {

    }

    public static HelloMessage receive(DataInputStream io) {
        //TODO        
        return null;
    }
}
```

```
public class MouseMoveMessage implements Message {
    private final int x;
    private final int y;


    MouseMoveMessage(int x, int y) {
        this.x = x;
        this.y = y;
    }

    public static MouseMoveMessage receive(DataInputStream inputStream) throws IOException {
        int x = inputStream.readInt();
        int y = inputStream.readInt();

        return new MouseMoveMessage(x, y);
    }

    public int getX() {
        return x;
    }

    public int getY() {
        return y;
    }
}

```

Using this design, the protocol code could theoretically also be used for other use cases and I think it is quite clean to do it that way. @jayesh83 what do you think? Also, it would be possible to copy the protocol part directly from https://github.com/dadosch/synergy-android-7/tree/master/app/src/main/java/org/synergy/io as the licenses are equal and compatible. That would be simpler and we could focus on the android part…

**Comment by jayesh83** [comment]
Yes @dadosch It is indeed intuitive. we should do it this way only. 
also Can you clarify this line "    public static MouseMoveMessage receive(DataInputStream inputStream) throws IOException {   " 
we're getting same underlying stream right I meant every time there's new message this input stream is same right? only data inside it changes and not new instance of inputstream is received everytime?

**Comment by jayesh83** [comment]
Now, challenge is how we're supposed to show mouse pointer?

See, when a mouse is directly connected to phone using OTG cable or connected wirelessly using hardware receiver, the mouse pointer in phone immedietly appears right.

In our case, we don't have hardware(mouse) connected to phone directly still we're to show pointer.

Any idea how to go about this?

What I could think of
1. Once the mouse pointer leaves desktop edge, let's say we get an event at android side in our inputStream that it's msg Enter. then initially we show/draw a mouse pointer statically at the left 50% height edge okay.
2. Then suppose mouse moves then how do we know how much mouse has moved? mouse pointer movement is still being captured in desktop, and those captured movement will be shared in inputstream?

**Comment by jayesh83** [comment]
Or to give this brainstorming an initial drift lets connect live on Google Meet or something to clearify things properly and come up with low-leve design
